### ISSUE TITLE
[PE-D][Tester B] Adding a contact section in UG: incorrect command format

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F09-2/tp#162]
`Format: add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS g/GENDER` as stated in the UG doesn't work, as no DOB is specified. `add` is not recognised too.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ish1506/ped#2

**Comment by lfrostbytee** [comment]
Tester refers to the additional parameters section which should not exist in the UG anymore.
