### ISSUE TITLE
[PE-D][Tester B] Bug in time format validation (24H format)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F09-2/tp#172]
Similar to issue #3, for the addEvent command:

![image.png](https://raw.githubusercontent.com/ish1506/ped/main/files/a78d9d2a-5463-470e-9625-af65957ee7a5.png)

A time of `t/00:65` is allowed.
![image.png](https://raw.githubusercontent.com/ish1506/ped/main/files/d70d6e1e-1613-4067-bea3-d14173ee9752.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ish1506/ped#4

**Comment by lfrostbytee** [comment]
Should be the same issue as #169. Once either is fixed, the other should be fixed as well.
