### ISSUE TITLE
[PE-D][Tester B] Grammer mistake for tagged person in Event

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F09-2/tp#178]
![image.png](https://raw.githubusercontent.com/ish1506/ped/main/files/c5a8b9ec-eb15-4a23-97b7-10f810fcc545.png)

Just a minor bug, "1 people" instead of "1 person"

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: ish1506/ped#6

**Comment by lfrostbytee** [comment]
In the case of 0 and more than 1 persons, we can indicate it as '0/n attendees'. For 1 persons, we can indicate it as '1 attendee'.
